# Generated by Django 4.0.4 on 2022-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
